// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Player        int32                  `protobuf:"varint,2,opt,name=player,proto3" json:"player,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // Tetris tetris = 1;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_proto_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{0}
}

func (x *GameMessage) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameMessage) GetPlayer() int32 {
	if x != nil {
		return x.Player
	}
	return 0
}

func (x *GameMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Tetromino struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grid          []*GridRow             `protobuf:"bytes,1,rep,name=grid,proto3" json:"grid,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Shape         string                 `protobuf:"bytes,4,opt,name=shape,proto3" json:"shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tetromino) Reset() {
	*x = Tetromino{}
	mi := &file_proto_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tetromino) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tetromino) ProtoMessage() {}

func (x *Tetromino) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tetromino.ProtoReflect.Descriptor instead.
func (*Tetromino) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{1}
}

func (x *Tetromino) GetGrid() []*GridRow {
	if x != nil {
		return x.Grid
	}
	return nil
}

func (x *Tetromino) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Tetromino) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Tetromino) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

type GridRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []bool                 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridRow) Reset() {
	*x = GridRow{}
	mi := &file_proto_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridRow) ProtoMessage() {}

func (x *GridRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridRow.ProtoReflect.Descriptor instead.
func (*GridRow) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{2}
}

func (x *GridRow) GetValues() []bool {
	if x != nil {
		return x.Values
	}
	return nil
}

type Tetris struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stack         []*StackRow            `protobuf:"bytes,1,rep,name=stack,proto3" json:"stack,omitempty"`
	Tetromino     *Tetromino             `protobuf:"bytes,2,opt,name=tetromino,proto3" json:"tetromino,omitempty"`
	LinesClear    int32                  `protobuf:"varint,3,opt,name=lines_clear,json=linesClear,proto3" json:"lines_clear,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tetris) Reset() {
	*x = Tetris{}
	mi := &file_proto_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tetris) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tetris) ProtoMessage() {}

func (x *Tetris) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tetris.ProtoReflect.Descriptor instead.
func (*Tetris) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{3}
}

func (x *Tetris) GetStack() []*StackRow {
	if x != nil {
		return x.Stack
	}
	return nil
}

func (x *Tetris) GetTetromino() *Tetromino {
	if x != nil {
		return x.Tetromino
	}
	return nil
}

func (x *Tetris) GetLinesClear() int32 {
	if x != nil {
		return x.LinesClear
	}
	return 0
}

type StackRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []string               `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StackRow) Reset() {
	*x = StackRow{}
	mi := &file_proto_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StackRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackRow) ProtoMessage() {}

func (x *StackRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackRow.ProtoReflect.Descriptor instead.
func (*StackRow) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{4}
}

func (x *StackRow) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

var File_proto_server_proto protoreflect.FileDescriptor

const file_proto_server_proto_rawDesc = "" +
	"\n" +
	"\x12proto/server.proto\"R\n" +
	"\vGameMessage\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x16\n" +
	"\x06player\x18\x02 \x01(\x05R\x06player\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"[\n" +
	"\tTetromino\x12\x1c\n" +
	"\x04grid\x18\x01 \x03(\v2\b.GridRowR\x04grid\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x14\n" +
	"\x05shape\x18\x04 \x01(\tR\x05shape\"!\n" +
	"\aGridRow\x12\x16\n" +
	"\x06values\x18\x01 \x03(\bR\x06values\"t\n" +
	"\x06Tetris\x12\x1f\n" +
	"\x05stack\x18\x01 \x03(\v2\t.StackRowR\x05stack\x12(\n" +
	"\ttetromino\x18\x02 \x01(\v2\n" +
	".TetrominoR\ttetromino\x12\x1f\n" +
	"\vlines_clear\x18\x03 \x01(\x05R\n" +
	"linesClear\" \n" +
	"\bStackRow\x12\x14\n" +
	"\x05cells\x18\x01 \x03(\tR\x05cells2@\n" +
	"\rTetrisService\x12/\n" +
	"\vGameSession\x12\f.GameMessage\x1a\f.GameMessage\"\x00(\x010\x01B%Z#github.com/Alvaroalonsobabbel/protob\x06proto3"

var (
	file_proto_server_proto_rawDescOnce sync.Once
	file_proto_server_proto_rawDescData []byte
)

func file_proto_server_proto_rawDescGZIP() []byte {
	file_proto_server_proto_rawDescOnce.Do(func() {
		file_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_server_proto_rawDesc), len(file_proto_server_proto_rawDesc)))
	})
	return file_proto_server_proto_rawDescData
}

var file_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_server_proto_goTypes = []any{
	(*GameMessage)(nil), // 0: GameMessage
	(*Tetromino)(nil),   // 1: Tetromino
	(*GridRow)(nil),     // 2: GridRow
	(*Tetris)(nil),      // 3: Tetris
	(*StackRow)(nil),    // 4: StackRow
}
var file_proto_server_proto_depIdxs = []int32{
	2, // 0: Tetromino.grid:type_name -> GridRow
	4, // 1: Tetris.stack:type_name -> StackRow
	1, // 2: Tetris.tetromino:type_name -> Tetromino
	0, // 3: TetrisService.GameSession:input_type -> GameMessage
	0, // 4: TetrisService.GameSession:output_type -> GameMessage
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_server_proto_init() }
func file_proto_server_proto_init() {
	if File_proto_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_server_proto_rawDesc), len(file_proto_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_server_proto_goTypes,
		DependencyIndexes: file_proto_server_proto_depIdxs,
		MessageInfos:      file_proto_server_proto_msgTypes,
	}.Build()
	File_proto_server_proto = out.File
	file_proto_server_proto_goTypes = nil
	file_proto_server_proto_depIdxs = nil
}
