name: Build

on:
    push:
        branches: ["main"]
        paths-ignore:
            - "**/README.md"
            - "**/.gitignore"
            - "doc/**"
            - "bin/**"

permissions:
    contents: write

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: stable

            - name: Check out code into the Go module directory
              uses: actions/checkout@v3

            - name: Build
              run: GOOS=darwin GOARCH=arm64 make build-tetris

            - name: Read Version
              run: echo "VERSION=$(go run main.go -version)" >> $GITHUB_ENV

            - name: Upload Release Asset
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: $VERSION
                  name: Terminal Tetris $VERSION
                  generate_release_notes: true
                  files: bin/tetris
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
